<?php
 require('bif.php');
 bifPageheader('Mission statement');
?>

<p>(This is a draft statement, proposed by Kurt Schneiderman)
</p>
<div class='vspace'></div><h2>What Is It?</h2>
<p>The buffalo “infringement” festival is a non-commercial, non-hierarchical
endeavor dedicated to experimental, controversial, and anti-establishment
artwork of all forms.  Taking place in multiple venues in and around
Buffalo’s Allentown District, the festival is an annual eleven-day event
running from the last weekend of July through the first weekend of August.
</p>
<p class='vspace'>Our festival in Buffalo is only one contingent of a growing international
“infringement” movement that holds festivals in a number of North American
cities including Montreal, QC, New York, NY, Ottawa, ON, Halifax, NS,
Regina, SA, and Philadelphia, PA.  For more information on the
international movement, visit our parent website at <a href='http://infringementfestival.com/'>http://infringementfestival.com/</a>
</p>
<div class='vspace'></div><h2>Our Philosophy.</h2>
<p>The buffalo “infringement” festival is dedicated to the belief that art has
a greater purpose than simply to entertain or simply to make a quick buck.
Unfortunately, the modern-day arts world is increasingly degenerated by
commercialism, elitism, and close-minded-ness.  In this climate, the vast
majority of art inevitably grows more and more toothless, perfunctory, and
irrelevant.  To counter this, we have undertaken to claw out a small niche
where artists are free – both ideologically and financially – to create as
they wish.
</p>
<p class='vspace'>There are many festivals – nationally and internationally – that seek to
promote “alternative art.”  But, all too often, these endeavors are a
victim of their own success.  As they grow in popularity, they become part
of the mainstream and, ultimately, suffer from the same commercialism and
complacency that they set out to break free from in the first place.  To
insure that the same fate does not befall our “infringement” festival, we
commit to the following ground rules:
</p>
<div class='vspace'></div><h2>Our Ground Rules.</h2>

<p>1) Artists Participate for Free!
</p><div class='indent'>There is no admission fee for artists and artists keep one hundred percent of the money that their project brings in at the door.  The festival provides each project with a venue to perform in, up to five performance slots (six for outdoor events), and listings in our brochure and on our website.  All other costs, issues, and needs are left for the artists to tackle of their own accord.
</div><p class='vspace'>2) No one is Rejected!
</p><div class='indent'>Anyone who gets in a Project Proposal before the submission deadline – as long their project is legal and physically do-able – will be accepted.  No one is empowered to judge artists’ work as “worthy” or “un-worthy.”  Everything is welcome.
</div><p class='vspace'>3) No one is in Charge!
</p><div class='indent'>The “infringement” festival is a non-hierarchical collective.  There is no salaried staff.  There is no official in a suit and tie telling people what to do.  No one is making any money off of this (other than, hopefully, the artists).  Instead, the festival is organized by a volunteer committee, which is open to anyone who wants in.  All decisions are made democratically.
</div><p class='vspace'>4) Keep it Cheap!
</p><div class='indent'>The only thing our artists are NOT allowed to do is charge too much at the door.  In order to foster a non-commercial atmosphere, the maximum admission fee that any “infringement” festival event can charge is $10.00 dollars per ticket.  Many “infringement” events are offered on a “pay-what-you-can” basis or through some other alternative admission fee.  Artists are strongly encouraged to take this approach.
</div><div class='vspace'></div><h2>Our History.</h2>
<p>The “infringement” movement began in 2003 when a group called the Optative
Theatrical Laboratory was expelled from the Montreal Fringe Festival for –
of all things – insulting the Festival’s corporate sponsor (Starbucks)!
Outraged by this disgusting commercialism, the Optative group decided it
was high time that someone form a non-commercial, non-authoritarian arts
festival.
</p>
<p class='vspace'>The next year, 2004, the first “infringement” festival was held in Montreal
and enjoyed so much success that the organizers decided to take it on the
road and hold satellite “infringement” festivals in Quebec City, Ottawa,
and Toronto.
</p>
<p class='vspace'>While performing at the Toronto Fringe Festival, members of Buffalo’s
Subversive Theatre Collective first encountered the “infringement” group
and immediately agreed that this was an idea that had to be brought back to
Buffalo.
</p>
<p class='vspace'>The first buffalo “infringement” festival was held from July 28th through
August 7th, 2005.  What was originally planned as a humble event with a
handful of different arts groups mushroomed into a vibrant festival
involving scores of artists and a myriad of art forms – theatre,
performance art, interpretive dance, cabaret, staged readings, street
theatre, rap, and poetry slams, as well as cutting edge film, music, and
multi-media work.   All in all, our 2005 festival featured 144 different
performances of forty-four different productions in eleven different venues
in and around Buffalo’s Allentown neighborhood.

</p>
<p class='vspace'>And we were not alone.  In the summer of 2005, other “infringement”
festivals were founded in Halifax, Nova Scotia and New York, New York.
</p>
<p class='vspace'>Now, in 2006, the infringement movement continues to spread with new
festivals scheduled to debut in Regina, Saskatchewan and Philadelphia,
Pennsylvania.
</p>
</div>

<?php
 bifPagefooter();
?>
